/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /**
     * Liveness check
     * @description Returns ok when the server is running.
     */
    get: operations["health_health_get"];
  };
  "/stats": {
    /**
     * Database statistics
     * @description Counts of chains, stores, items, and prices; last successful fetch per chain.
     */
    get: operations["stats_stats_get"];
  };
  "/chains": {
    /**
     * All loaded chains
     * @description Returns one entry per chain in the database with barcode and store counts.
     */
    get: operations["chains_chains_get"];
  };
  "/stores": {
    /**
     * Store branches
     * @description List supermarket branches. Filter by chain and/or city.
     * Only returns stores that have at least store metadata loaded.
     */
    get: operations["stores_stores_get"];
  };
  "/cities": {
    /**
     * Cities with price data
     * @description Cities that have actual price data loaded, with chain/store/price counts.
     */
    get: operations["cities_cities_get"];
  };
  "/search": {
    /**
     * Search products by name
     * @description Search for products by Hebrew or English name. Multi-word queries match ALL words
     * in any order. Returns multi-chain products first, then single-chain.
     * Supports pagination via offset. group_by=store returns one row per store.
     */
    get: operations["search_search_get"];
  };
  "/compare": {
    /**
     * Cross-chain price comparison
     * @description Like /search but returns ONLY products available in 2+ chains, with
     * delta_from_cheapest on each quote showing how much more expensive vs the cheapest chain.
     */
    get: operations["compare_compare_get"];
  };
  "/product/{barcode}": {
    /**
     * All prices for one barcode
     * @description Fetch every price quote across all stores for a single barcode.
     * Returns 404 if the barcode is not found in any chain.
     * Returns 400 if the barcode format is invalid (not 8–14 digits).
     */
    get: operations["product_product__barcode__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * ChainSummary
     * @description One loaded chain with aggregate stats.
     */
    ChainSummary: {
      /**
       * Chain Id
       * @description Chain barcode prefix / government ID
       */
      chain_id: string;
      /**
       * Name
       * @description Hebrew chain name
       */
      name: string;
      /**
       * Total Barcodes
       * @description Distinct barcodes with prices loaded
       */
      total_barcodes: number;
      /**
       * Total Stores Loaded
       * @description Stores we have price data for
       */
      total_stores_loaded: number;
    };
    /**
     * CityInfo
     * @description A city with price coverage statistics.
     */
    CityInfo: {
      /** City */
      city: string;
      /**
       * Chain Count
       * @description Number of distinct chains with prices in this city
       */
      chain_count: number;
      /**
       * Store Count
       * @description Number of stores with prices in this city
       */
      store_count: number;
      /**
       * Price Count
       * @description Total price rows in this city
       */
      price_count: number;
      /**
       * Chain Ids
       * @description chain_ids present in this city
       */
      chain_ids?: string[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * PriceQuote
     * @description One chain's best (cheapest store) price for a barcode.
     */
    PriceQuote: {
      /** Chain Id */
      chain_id: string;
      /** Chain Name */
      chain_name: string | null;
      /** Store Id */
      store_id: string;
      /** Store Name */
      store_name: string | null;
      /** City */
      city: string | null;
      /**
       * Price
       * @description Item price in NIS
       */
      price: number;
      /**
       * Unit Price
       * @description Price per unit-of-measure
       */
      unit_price?: number | null;
      /** Unit Of Measure */
      unit_of_measure: string | null;
      /**
       * Updated At
       * @description Date price was last updated in source XML
       */
      updated_at?: string | null;
      /**
       * Delta From Cheapest
       * @description How much more expensive than the cheapest chain (0 = cheapest)
       * @default 0
       */
      delta_from_cheapest?: number;
    };
    /**
     * Product
     * @description Core product metadata, chain-agnostic.
     */
    Product: {
      /**
       * Item Code
       * @description Barcode / EAN
       */
      item_code: string;
      /**
       * Canonical Name
       * @description Name from first chain to insert this barcode
       */
      canonical_name?: string | null;
      /** Manufacturer */
      manufacturer: string | null;
      /** Unit Of Measure */
      unit_of_measure: string | null;
      /**
       * Is Weighted
       * @description True for deli/cheese items priced per kg
       */
      is_weighted: boolean;
      /**
       * Names Per Chain
       * @description chain_id → product name as that chain calls it
       */
      names_per_chain?: {
        [key: string]: string;
      };
    };
    /**
     * ProductWithPrices
     * @description A product together with all available price quotes.
     */
    ProductWithPrices: {
      product: components["schemas"]["Product"];
      /**
       * Quotes
       * @description One entry per chain, sorted cheapest first
       */
      quotes: components["schemas"]["PriceQuote"][];
      /** Cheapest Price */
      cheapest_price: number | null;
      /** Most Expensive Price */
      most_expensive_price: number | null;
      /**
       * Chains Count
       * @description Number of distinct chains carrying this barcode
       */
      chains_count: number;
    };
    /**
     * SearchResult
     * @description Response for GET /search and GET /compare.
     */
    SearchResult: {
      /** Query */
      query: string;
      /**
       * Total Matches
       * @description Distinct barcodes matching the query
       */
      total_matches: number;
      /**
       * Comparable Count
       * @description Barcodes available in 2+ chains
       */
      comparable_count: number;
      /**
       * Has More
       * @description True when more results exist beyond current page
       * @default false
       */
      has_more?: boolean;
      /**
       * Items
       * @description Multi-chain products first (sorted by cheapest price), then single-chain
       */
      items: components["schemas"]["ProductWithPrices"][];
    };
    /**
     * StatsResponse
     * @description Database statistics snapshot.
     */
    StatsResponse: {
      /** Chains Count */
      chains_count: number;
      /**
       * Stores Count
       * @description Stores with at least one price loaded
       */
      stores_count: number;
      /**
       * Items Count
       * @description Distinct barcodes in items table
       */
      items_count: number;
      /**
       * Prices Count
       * @description Total price rows across all stores
       */
      prices_count: number;
      /**
       * Last Fetch Per Chain
       * @description chain name → ISO timestamp of last successful fetch
       */
      last_fetch_per_chain: {
        [key: string]: string | null;
      };
    };
    /**
     * Store
     * @description A single supermarket branch.
     */
    Store: {
      /** Store Id */
      store_id: string;
      /** Chain Id */
      chain_id: string;
      /**
       * Chain Name
       * @description Hebrew chain name
       */
      chain_name?: string | null;
      /**
       * Store Name
       * @description Branch name / location label
       */
      store_name?: string | null;
      /** City */
      city: string | null;
      /** Address */
      address: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Liveness check
   * @description Returns ok when the server is running.
   */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Database statistics
   * @description Counts of chains, stores, items, and prices; last successful fetch per chain.
   */
  stats_stats_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["StatsResponse"];
        };
      };
    };
  };
  /**
   * All loaded chains
   * @description Returns one entry per chain in the database with barcode and store counts.
   */
  chains_chains_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ChainSummary"][];
        };
      };
    };
  };
  /**
   * Store branches
   * @description List supermarket branches. Filter by chain and/or city.
   * Only returns stores that have at least store metadata loaded.
   */
  stores_stores_get: {
    parameters: {
      query?: {
        /** @description Filter by chain_id */
        chain?: string | null;
        /** @description Filter by city (Hebrew or English) */
        city?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Store"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Cities with price data
   * @description Cities that have actual price data loaded, with chain/store/price counts.
   */
  cities_cities_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CityInfo"][];
        };
      };
    };
  };
  /**
   * Search products by name
   * @description Search for products by Hebrew or English name. Multi-word queries match ALL words
   * in any order. Returns multi-chain products first, then single-chain.
   * Supports pagination via offset. group_by=store returns one row per store.
   */
  search_search_get: {
    parameters: {
      query: {
        /** @description Product name or manufacturer (multi-word AND) */
        q: string;
        /** @description Max products returned */
        limit?: number;
        /** @description Pagination offset */
        offset?: number;
        /** @description Filter to stores in this city */
        city?: string | null;
        /** @description Filter to one chain_id */
        chain?: string | null;
        /** @description Group results by chain or individual store */
        group_by?: "chain" | "store";
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SearchResult"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Cross-chain price comparison
   * @description Like /search but returns ONLY products available in 2+ chains, with
   * delta_from_cheapest on each quote showing how much more expensive vs the cheapest chain.
   */
  compare_compare_get: {
    parameters: {
      query: {
        /** @description Product name or manufacturer */
        q: string;
        /** @description Max products returned */
        limit?: number;
        /** @description Pagination offset */
        offset?: number;
        /** @description Filter to stores in this city */
        city?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SearchResult"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * All prices for one barcode
   * @description Fetch every price quote across all stores for a single barcode.
   * Returns 404 if the barcode is not found in any chain.
   * Returns 400 if the barcode format is invalid (not 8–14 digits).
   */
  product_product__barcode__get: {
    parameters: {
      path: {
        /** @description EAN/barcode — 8 to 14 digits */
        barcode: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductWithPrices"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
